### ISSUE TITLE
TypeError: writeXml() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by minias** [mangosystem/qgis-tmsforkorea-plugin#4]
레이어 창에서 레이어 위치를 바꾸면 계속 아래 오류가 뜹니다.

QGIS 버전 | 3.22.5-Białowieża | QGIS 코드 리버전 | 2a0a86f142
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 12.3
  |   |   |  
Active Python plugins
tmsforkorea | 3.0.4
openlayers_plugin | 2.0.0
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

> TypeError: writeXml() takes 3 positional arguments but 4 were given

**Comment by mapplus** [comment]
QgsPluginLayer를 상속받아 구현하는 경우에 readXml, writeXml의 파라미터가 3개에서 4개로 늘어놨습니다.

다음 버전에서 패치 예정입니다.

#. 참고: https://qgis.org/pyqgis/3.22/core/QgsPluginLayer.html#qgis.core.QgsPluginLayer.writeXml
